version: '3.8'

services:
  mysql:
    image: mysql
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports: 
      - "8080:8080"
    volumes: 
      - mysql-data:/var/lib/mysql
    networks: 
      - app-network
  redis:
    image: redis:latest
    container_name: redis-container
    ports: 
      - "5436:5433"
    networks: 
      - app-network

volumes:
  mysql-data:

networks:
  app-network:
    driver: bridge